### ISSUE TITLE
Handling tags in a separate table

### ISSUE THREAD

**Issue by derletztekick** [ilosuna/mylittleforum#289]
Tags in postings and bookmarks are stored in a column in the entry/bookmark table. It seems to be better, to create new TAG-table(s), to handle tags in a more intuitiv way - as suggested by @auge8472 in #254 .

**Comment by derletztekick** [comment]
FJI: I start an implementation

**Comment by auge8472** [comment]
I held several brain melting sessions in the last few days. Because of the fact, that the program uses tags in at least two places (postings and now also bookmarks) I propose a structure with two tables.

## table tags

fieldname|description
---|---
id|dataset index
name|string tag

## table tag_mapping

fieldname|description
---|---
id|dataset index
tag_id|index of entry in table bookmarks
entry_id|posting index
bm_id|bookmark index

A new entry in table `tags` only occurs, when the tag is unknown. So the script could refer to the same tag every time it is searched for. Afterwards or when the tag is already known, only a new entry in `tag_mapping` will happen.

**Comment by derletztekick** [comment]
Hej,

my current `table_tags` is like yours but I don't want to mix the postings and the bookmarks because there is no logical relation between both. Thus, my `bookmark_tags_table` ist like this

## bookmark_tags_table 

fieldname|description
---|---
tag_id|index of entry in table bookmarks
bm_id|bookmark index

The primary key is set to `(tag_id, bm_id)`, thus, no further index (or id) is needed.

If we want to join bookmarks and posting tags, I suggest the following table design

fieldname|description
---|---
tag_id|index of entry in table bookmarks
e_id|entry id bookmark OR posting index
flag| ENUM <Bookmark/POSTING>

Anyway, I prefer separate tables for `posting_tags` and `bookmark_tags`.

**Comment by derletztekick** [comment]
I add a new branch with the current changes for bookmark and tag handling, i.e. https://github.com/ilosuna/mylittleforum/tree/tag_table
