### ISSUE TITLE
Adding honey-pot to registration/postings form

### ISSUE THREAD

**Issue by derletztekick** [ilosuna/mylittleforum#303]
To avoid spam, e.g. [fake users](http://mylittleforum.net/forum/index.php?id=10459), we can add honey-pot fields to the forms (e.g. registration and posting).

**Comment by Helmut01** [comment]
Just for clarification: Do you mean a _real_ [honey-pot](http://www.projecthoneypot.org/manage_honey_pots.php) or just an (invisible) [link](http://www.projecthoneypot.org/manage_quicklink.php)? I have the latter a couple of years in some of my pages and received just 277 hits (none in the last two years).

**Comment by derletztekick** [comment]
What does _real_ meaning here? Both links redirect the visitor to a log-in page.

277 hits without any context is not meaningful. The interesting question is: How many spam messages are not prevented at the same time?

**Comment by auge8472** [comment]
> Just for clarification: Do you mean a real honey-pot or just an (invisible) link?

My interpretation of …

> > we can add honey-pot fields to the forms

… is to add hidden fields to the forms, that have to stay empty. If (one of) these fields will have an unexpected value, we can assume a spam attempt.

**Comment by Helmut01** [comment]
Hi Micha,

sorry about the wrong links (stupid me: autologin active). Here the FAQs from Project Honey Pot:
[Installing A Honey Pot On Your Site](http://www.projecthoneypot.org/faq.php#c)
[Including QuickLinks](http://www.projecthoneypot.org/faq.php#f)
I have quick-links on most of my pages (duno since _when_). Does not prevent spam – only updates the list of bad IPs.
I have ZB Block’s scripts active on my registration- and login-pages since November 2012. Worked nicely till March this year. Then I faced ~20 registrations / day (mainly from Russian IPs). In April I activated a modified Math-Captcha (see the end of the [registration form](http://forum.bebac.at/register.php) at my forum). Reduced the number of fake users to ~3 / day.

However, in the last five years I had only two cases where the accounts actually spammed. One made a post full of links and the other one edited his/her/its signature full of crap. I use Gunner’s [Forum Spam List Checker](http://www.gunnerinc.com/fslc.htm) to report the data (IP, Name, Email) to _BotScout_, _FSpamlist_, _Stop Forum Spam_, _IPInfoDB_, and _Project Honey Pot_ (you need their API Keys).

Hi Auge: Got it.

**Comment by auge8472** [comment]
@Helmut01: nice to see you here. :-)

**Comment by Helmut01** [comment]
Well, I still monitor regularly what’s going on with v2.x… ;-)

**Comment by derletztekick** [comment]
Hej Helmut,

currently, we have three services, i.e. Akismet, Bad Behavior and Stop Forum Spam. I believe (read: I hope), that they do a good job. I would like to keep the number of external services as small as possible. So, what is the  unique feature of your service w.r.t. Akismet, Bad Behavior and Stop Forum Spam?

/Micha

**Comment by derletztekick** [comment]
Hi,

I add a first implementation, see #305 Any objections?

/Micha
