### ISSUE TITLE
Notification message: new entry

### ISSUE THREAD

**Issue by loesler** [ilosuna/mylittleforum#358]
I noticed that some users misinterpret the notification email. These users reply the email instead of posting a new answer to the forum thread. My suggestion is, to add a  specific note to the email, e.g.: _This is an information message. You receive  this email because you enable the notification function. Please do not reply this email but respond to the specific thread._

**Comment by auge8472** [comment]
Sounds reasonable. IMHO this paragraph should be added to every automatic e-mail message directly following the salutation. Following your proposal we would need two versions because of the sentence "You receive this email because you enable the notification function.". During registration process (as an example) one hasn't activated this function.

**Comment by loesler** [comment]
> we would need two version

Yes, of course. My "paragraph" was only an example to illustrate my intention.

**Comment by loesler** [comment]
I add a notification to the English and German language file. I believe, we can close this issue.

**Comment by auge8472** [comment]
Thank you.
