### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by PhilDunphy** [ilosuna/mylittleforum#382]
When installing from /install/index_php I get a MySQL error
SQL error' (MySQL: Column count doesn't match value count at row 1)

Any ideas?

**Comment by auge8472** [comment]
Which version you tried to install? Was it the actual 2.4.12 or the master branch?

**Comment by PhilDunphy** [comment]
Followed install steps. Took down the zip and extracted it into forum. Dropped it into my html folder on Apache

**Comment by auge8472** [comment]
>Took down the zip …

Ok, but which ZIP? Was it one [from the releases list](https://github.com/ilosuna/mylittleforum/releases) (and if so, which one) or did you download the ZIP from [the main page here on Github](https://github.com/ilosuna/mylittleforum) with the "clone or download" button? I ask, because I know, that the master branch is actually not installable. The installation script of the master branch misses the new fields that was introduced with version 2.4.10 in the line, [where the default user gets inserted](https://github.com/ilosuna/mylittleforum/blob/master/install/install.sql#L153) into the database table.

That would explain the message "Column count doesn't match value count". The latest release 2.4.12 contains the missed fields (the `NULL, NULL` part at the end of [the line 151](https://github.com/ilosuna/mylittleforum/blob/2.4.12/install/install.sql#L151)).

If I'm right, please try to install again with [the latest release](https://github.com/ilosuna/mylittleforum/releases/tag/2.4.12).

**Comment by PhilDunphy** [comment]
Thanks for reply. Issue was as you said. However after install page is blank. Is ther another step to follow in order for content to show?

**Comment by PhilDunphy** [comment]
@auge8472 Found the issue. Checked logs and seems wrong version of php-xml was installed. Fixed now. Thanks for your help. Closing issue
