### ISSUE TITLE
SPAM filter

### ISSUE THREAD

**Issue by loesler** [ilosuna/mylittleforum#426]
Since SELFHTML does not re-upload the source code for the [Bayes filter](https://wiki.selfhtml.org/wiki/Programmiertechnik/Bayesscher_Kommentarspam-Filter), see  [here](https://forum.selfhtml.org/meta/2017/dec/12/wiki-artikel-bayesscher-kommentarspam-filter-beschaedigt/1709928) and [here](https://forum.selfhtml.org/meta/2018/oct/28/wiki-artikel-bayesscher-kommentarspam-filter-enthaelt-fehlerhaften-link-zu-den-klassen/1735298), I checked other (open-source) implementations. The [B8 frameworks](https://github.com/bohwaz/b8-backup) provides the necessary functions, is open-source and uses php/mysql. Thus, I have started to add the [B8 module](https://github.com/ilosuna/mylittleforum/pull/427) to the forum software. I restrict the implementation to the entries (email via contact-form are not checked so far by B8). 

The main problem is/was, that akismet was integrated to the entry table (and in most of the sql statements). I have tried to divide the entries and the akismet columns. The akismet columns are transferred to a new table. In the same way, I defined a B8 related table.

B8 is not an external service. Each admin has to train the filter with spam AND ham individually. Thus, the spam/ham option(s) should be shown all the time to train the filter even if akismet flag the entry as spam/ham. I add the option for automated training. However, B8 always needs an initial training as a let say _warm start_. 

Currently, I'm looking for some test users, which install the [new version](https://github.com/ilosuna/mylittleforum/pull/427). I don't look for coders but for users, which are able to install the software and which are familiar with phpmyadmin (i.e. to check the B8 training process). Coders are also welcome, but - I know from own experience - it is hard to validate code from others.

**Comment by auge8472** [comment]
> B8 always needs an initial training as a let say *warm start*.

After my installation of a test instance we had [a conversation about the plausability of training data that can be delivered with the forum](https://mylittleforum.net/forum/index.php?id=11566) itself. [You denied it](https://mylittleforum.net/forum/index.php?id=11569) because the diversity of ham and spam and also the different languages of the entries (spam and ham) that would –because of this– lead to meaningless training data.

But isn't the collection of (meaningless) training data one purpose of this issue? What do you want to achieve with the look into the real training data from different forums with different topics in different languages?

**Comment by loesler** [comment]
I don't understand the intension of your question.

**Comment by loesler** [comment]
The source code is updated, so, if any questions occur, please open an new issues.
