### ISSUE TITLE
Message gets not marked as possible spam when listing thread in nested or linear mode

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#464]
When one wrote a message and the script classifies it as spam, one get a message about that fact in the single-posting-view after the forward from the posting form. It's to inform the poster about an additional check through the forum team.

When one gets forwarded to the nested or linear view of the whole thread, the message doesn't exist. This is an inconsistency.

**Comment by loesler** [comment]
This is quite difficult because in linear view, only the thread-id is available. We have (at least) two options.

1. We transfer the entry-id via URI parameter, i.e., 
```
header('Location: index.php?mode=thread&id=' . $data['tid'] . '&eid=' . $id . '#p' . $id);
```
In this case, we have a static link that display the spam entry. Thus, I don't prefer that solution. 

2. We simple extend the if condition by `&& $spam == 0` in [posting.inc.php](https://github.com/ilosuna/mylittleforum/blob/master/includes/posting.inc.php#L1085), i.e.,
```
if (isset($back) && $back == 'thread' && $spam == 0)
	header('Location: index.php?mode=thread&id=' . $new_data['id'] . '#p' . $new_data['id']);
else
	header('Location: index.php?id=' . $new_data['id']);
```
If the entry is classified as spam, the user is redirect to index view and get the warning message. We don't need further changes in source code. That is my favourite solution. ;-)

**Comment by auge8472** [comment]
> If the entry is classified as spam, the user is redirect to index view and get the warning message. We don't need further changes in source code. That is my favourite solution. ;-)

Sounds reasonable. Is it done the same way for single entry view? Didn't find the relevant code ad hoc.

**Comment by loesler** [comment]
> Is it done the same way for single entry view?

I'm sorry for my bad description. To be more concrete: It is the single entry view. The user is redirected to his/her entry including the warning message. So, we use exact the same/existing mechanism.

**Comment by loesler** [comment]
Thanks you for thumbs up - I merged https://github.com/ilosuna/mylittleforum/pull/491
