### ISSUE TITLE
Make it easier to delete spam postings

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#473]
The entries in the list of encountered spam postings have no UI to delete these postings when marked or one by one from the list. This list should provide the same interface to delete postings as the main views have.

See also [the feature request in the project forum](https://mylittleforum.net/forum/index.php?id=11624) with a sceeenshot of the wanted UI-elements.

**Comment by loesler** [comment]
Currently, there are two options:
- Display spam in thread list
- List spam

I believe, we can forgo one of these options because both are (nearly) the same. My _simple_ suggestion is to modify the [main.inc.php](https://github.com/ilosuna/mylittleforum/blob/master/includes/main.inc.php#L239), i.e.,

```
// show spam?  NOTE: variables are used in several php files, i.e. index.inc.php, thread.inc.php, entry.inc.php
$display_spam_query_and = " AND (" . $db_settings['akismet_rating_table'] . ".spam = 0 AND " . $db_settings['b8_rating_table'] . ".spam = 0) ";
$display_spam_query_where = " WHERE (" . $db_settings['akismet_rating_table'] . ".spam = 0 AND " . $db_settings['b8_rating_table'] . ".spam = 0) ";
if (isset($_SESSION[$settings['session_prefix'].'usersettings']['show_spam'])) {
	//$display_spam_query_and = '';
	//$display_spam_query_where = '';
	
	$display_spam_query_and = " AND (" . $db_settings['akismet_rating_table'] . ".spam = 1 OR " . $db_settings['b8_rating_table'] . ".spam = 1) ";
	$display_spam_query_where = " WHERE (" . $db_settings['akismet_rating_table'] . ".spam = 1 OR " . $db_settings['b8_rating_table'] . ".spam = 1) ";
}
```

and we clean the [search.inc.php](https://github.com/ilosuna/mylittleforum/blob/master/includes/search.inc.php#L13) and remove the `$_GET['list_spam']` part.

In this case, it is not possible to display SPAM and HAM entries together but is it really necessary to display both?

**Comment by loesler** [comment]
Done by https://github.com/ilosuna/mylittleforum/pull/488

**Comment by loesler** [comment]
Works only, if spam posting is the opener :-(

**Comment by loesler** [comment]
Done by https://github.com/ilosuna/mylittleforum/pull/495
