### ISSUE TITLE
Servers with no email server support

### ISSUE THREAD

**Issue by leha-code** [ilosuna/mylittleforum#576]
i dont have an email server, and i still want mlf to work without email verification

**Comment by auge8472** [comment]
As long as users should be able to register themself, you'll definitely need access to an e-mail-server. Normally this will be handled by your hosting service provider so that you'll have automatically access to an e-mail-service.

Please create a PHP-script-file with *only* the following code …

~~~
<?php phpinfo(); ?>
~~~

… save it, load it up to your webspace and open it in your browser. You'll see the configuration of your PHP-installation.

If you find a key named `sendmail_path` with a value (i.e. `/usr/sbin/sendmail`) you really have access to an e-mail-service. Search in the documentation of your hosting provider to determine, if you have to add a parameter in the configuration of the forum script (advanced forum settings=>`mail_parameter`) to use the e-mail service.

Please don't forget to delet this file from the web server after the investigation. The content tells anyone who finds the file much to much about the configuration of your webspace.

Otherwise you as the forum operator have to manually register every single user or you have to use the forum without any registration possibility.
