### ISSUE TITLE
Reddit like links

### ISSUE THREAD

**Issue by finkiki** [ilosuna/mylittleforum#70]
Add the possibility to create a new topic which open a link as reddit or hacker news does.

**Comment by auge8472** [comment]
I for myself don't use Reddit. After reading in the Wikipedia I assume, you want to create entries in the forum from posting external links as their subjects?

**Comment by finkiki** [comment]
Absolutely. And other users could comment on that link as in a normal topic. This maybe need a little icon to show that this topic is an external link.

**Comment by auge8472** [comment]
> This maybe need a little icon to show that this topic is an external link.

Not only this. It needs *a second link*, because normally the link leads to the entry and not to an external resource. That would require a completely rewrite to alter the behaviour (link to entry vs. one link to external resource **and** a second link to the entry (for comments)). Because one can write her/his external link *into* the entry, *I* (for myself) would say, that it's not worth the effort.

Please wait for the opinions of the others.

**Comment by derletztekick** [comment]
I'm not familiar with reddit, so I can not support this issue.

**Comment by auge8472** [comment]
@finkiki Thank you for your proposal. Because of the unwanted behaviour change (a subject with two or more(?) links to different targets) and the fact, that one can always put links into the entry itself, we think, there's no need for it. Thatswhy I'll close the issue now.
